apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","k8s-app":"fluentd-gcp-scaler","version":"v0.5.0"},"name":"fluentd-gcp-scaler","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"k8s-app":"fluentd-gcp-scaler"}},"template":{"metadata":{"labels":{"k8s-app":"fluentd-gcp-scaler"}},"spec":{"containers":[{"command":["/scaler.sh","--ds-name=fluentd-gcp-v3.2.0","--scaling-policy=fluentd-gcp-scaling-policy"],"env":[{"name":"CPU_REQUEST","value":"100m"},{"name":"MEMORY_REQUEST","value":"200Mi"},{"name":"CPU_LIMIT","value":"1000m"},{"name":"MEMORY_LIMIT","value":"500Mi"}],"image":"k8s.gcr.io/fluentd-gcp-scaler:0.5","name":"fluentd-gcp-scaler"}],"serviceAccountName":"fluentd-gcp-scaler"}}}}
  creationTimestamp: "2019-01-23T21:33:15Z"
  generation: 1
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: fluentd-gcp-scaler
    version: v0.5.0
  name: fluentd-gcp-scaler
  namespace: kube-system
  resourceVersion: "706273"
  selfLink: /apis/apps/v1/namespaces/kube-system/deployments/fluentd-gcp-scaler
  uid: 7df02451-1f56-11e9-b786-42010a800256
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: fluentd-gcp-scaler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: fluentd-gcp-scaler
    spec:
      containers:
      - command:
        - /scaler.sh
        - --ds-name=fluentd-gcp-v3.2.0
        - --scaling-policy=fluentd-gcp-scaling-policy
        env:
        - name: CPU_REQUEST
          value: 100m
        - name: MEMORY_REQUEST
          value: 200Mi
        - name: CPU_LIMIT
          value: 1000m
        - name: MEMORY_LIMIT
          value: 500Mi
        image: k8s.gcr.io/fluentd-gcp-scaler:0.5
        imagePullPolicy: IfNotPresent
        name: fluentd-gcp-scaler
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: fluentd-gcp-scaler
      serviceAccountName: fluentd-gcp-scaler
      terminationGracePeriodSeconds: 30
