apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"deckhand"},"name":"deckhand","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"deckhand"}},"template":{"metadata":{"labels":{"app":"deckhand"}},"spec":{"containers":[{"env":[{"name":"DECK_GIT_REPO","value":"https://github.com/nfons/example-gitops.git"},{"name":"DECK_GIT_PASSWORD","value":"Heartbreak5.5"},{"name":"DECK_GIT_USER","value":"nfons"}],"image":"nfons/deckhand:latest","name":"deckhand","ports":[{"containerPort":8080}]}]}}}}
  creationTimestamp: "2019-01-24T00:32:53Z"
  generation: 2
  labels:
    app: deckhand
  name: deckhand
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/deckhand
  uid: 968b17b5-1f6f-11e9-b786-42010a800256
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: deckhand
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deckhand
    spec:
      containers:
      - env:
        - name: DECK_GIT_REPO
          value: https://github.com/nfons/example-gitops.git
        - name: DECK_GIT_PASSWORD
          value: Heartbreak5.5
        - name: DECK_GIT_USER
          value: nfons
        image: nfons/deckhand:latest
        imagePullPolicy: Always
        name: deckhand
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
