apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"http-svc","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"http-svc"}},"template":{"metadata":{"labels":{"app":"http-svc"}},"spec":{"containers":[{"image":"gcr.io/google_containers/echoserver:1.8","name":"app","ports":[{"containerPort":8080}]}]}}}}
  creationTimestamp: "2019-01-17T16:58:25Z"
  generation: 1
  name: http-svc
  namespace: default
  resourceVersion: "86943"
  selfLink: /apis/apps/v1/namespaces/default/deployments/http-svc
  uid: 1b1d6a30-1a79-11e9-a6ea-025000000001
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: http-svc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: http-svc
    spec:
      containers:
      - image: gcr.io/google_containers/echoserver:1.8
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
