apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2019-01-23T21:32:43Z"
  name: default
  resourceVersion: "24"
  selfLink: /api/v1/namespaces/default
  uid: 6b3f111d-1f56-11e9-b786-42010a800256
spec:
  finalizers:
  - kubernetes
