apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"spekt8","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"component":"spekt8"}},"template":{"metadata":{"labels":{"component":"spekt8"}},"spec":{"containers":[{"image":"elliotxkim/spekt8","name":"spekt8","ports":[{"containerPort":3000}]}]}}}}
  creationTimestamp: "2018-12-01T03:12:36Z"
  generation: 1
  name: spekt8
  namespace: default
  resourceVersion: "2909"
  selfLink: /apis/apps/v1/namespaces/default/deployments/spekt8
  uid: f3bb9d7e-f516-11e8-a1f9-025000000001
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: spekt8
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: spekt8
    spec:
      containers:
      - image: elliotxkim/spekt8
        imagePullPolicy: Always
        name: spekt8
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
